CREATE DATABASE IF NOT EXISTS db1004;

USE db1004;

CREATE TABLE member (
	email	VARCHAR(30) NOT NULL,
	password VARCHAR(100) NOT NULL,
	name VARCHAR(20) NOT NULL,
	PRIMARY KEY (email)
);

CREATE TABLE post (
	id INT NOT NULL,
	member_email VARCHAR(30) NOT NULL,
	title	VARCHAR(50)	NOT NULL,
	author VARCHAR(20) NOT NULL,
	createAt TIMESTAMP NOT NULL,
	content VARCHAR(1000) NOT NULL,
	view INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (member_email) REFERENCES member(email)
);

CREATE TABLE comment (
	id INT NOT NULL,
	post_id INT NOT NULL,
	author VARCHAR(20) NOT NULL,
	createAt TIMESTAMP NOT NULL,
	content VARCHAR(200) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (post_id) REFERENCES post(id)
);